apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: backend
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rajazainjanjua333@gmail.com
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx

# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: rajazainjanjua333@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-prod-account-key
#     # solvers:
#     # - http01:
#     #     ingress: {}
#     solvers:
#     - http01:
#         ingress:
#           class: public  
#     # solvers:
#     # - selector:
#     #     dnsZones:
#     #     - 'test.mujahidhussain.store'
#     #   dns01:
#     #     webhook:
#     #       config:
#     #         apiKeySecretRef:
#     #           name: godaddy-api-key
#     #           key: token
#     #         ttl: 600
#     #       groupName: acme.mycompany.com
#     #       solverName: godaddy