apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: aputra/myapp-193:v6
        name: guestbook-ui
        ports:
        - name: http
          containerPort: 80
